import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

import "./aboutPage.css";

export function AboutPage() {
  const navigate = useNavigate();
  return <article className="about-page"><button aria-label="Back to More" className="about-back" onClick={() => navigate("/child/more")} type="button"><ArrowLeft /></button><h1>About Abune</h1><p><b>Abune</b> is a spiritual support and communication application designed to strengthen the relationship between Spiritual Fathers and their spiritual children within the Ethiopian Orthodox Tewahedo Church.</p><p>The application provides a respectful, organized, and private space where spiritual children can communicate with their Spiritual Father, follow important spiritual dates, and review their spiritual journey.</p><h2>What Abune Can Do</h2><ul><li>Create and securely access a personal account.</li><li>Select a preferred appointment date, time, meeting method, and location.</li><li>Receive messages and responses from the Spiritual Father.</li><li>Follow personal spiritual milestones and history.</li><li>Receive notifications about appointments, messages, and important updates.</li></ul><h2>Privacy and Security</h2><p>Abune is designed to protect personal and spiritual information. Users must sign in before accessing private features, and each user can access only the information permitted for their role.</p><p>Users should avoid sharing passwords or allowing unauthorized people to access their devices. Sensitive spiritual matters should be discussed directly and privately with the Spiritual Father.</p><h2>Our Purpose</h2><p>Our purpose is to make spiritual communication more accessible, organized, and respectful while preserving the values, traditions, and pastoral relationship of the Ethiopian Orthodox Tewahedo Church.</p><h2>Application Information</h2><pre>Application: Abune<br />Platform: Android and Web<br />Version: 1.0.0<br />Developed for: Spiritual Fathers and Spiritual Children<br />© 2026 Abune. All rights reserved.</pre></article>;
}
