import { useEffect, useMemo, useState } from "react";
import { AppointmentCard, type ChildAppointment } from "../components/appointments/AppointmentCard";
import { api } from "../services";

type AppointmentReason = "confession" | "spiritual-guidance" | "counseling" | "repentance" | "family-issue" | "other";
type Slot = { id: string; date: string; startTime: string; endTime: string; meetingMethod: string; location?: string | null };
const reasons: Array<{ value: AppointmentReason; label: string }> = [{ value: "confession", label: "Confession" }, { value: "spiritual-guidance", label: "Spiritual Guidance" }, { value: "counseling", label: "Counseling" }, { value: "repentance", label: "Repentance" }, { value: "family-issue", label: "Family Issue" }, { value: "other", label: "Other" }];

export function AppointmentsPage() {
  const [reason, setReason] = useState<AppointmentReason>("confession"); const [slots, setSlots] = useState<Slot[]>([]); const [requests, setRequests] = useState<ChildAppointment[]>([]); const [selectedSlot, setSelectedSlot] = useState<Slot | null>(null); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
  const range = useMemo(() => { const today = new Date(); return { startDate: today.toISOString().slice(0, 10), endDate: new Date(today.getFullYear(), today.getMonth() + 2, 0).toISOString().slice(0, 10) }; }, []);
  async function load() { setLoading(true); setNotice(""); try { const [slotData, requestData] = await Promise.all([api<{ slots: Slot[] }>(`/api/appointments/slots?startDate=${range.startDate}&endDate=${range.endDate}`), api<{ requests: ChildAppointment[] }>("/api/appointments/request?type=requests")]); setSlots(slotData.slots ?? []); setRequests(requestData.requests ?? []); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to load appointments."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [range.startDate, range.endDate]);
  async function submitRequest() { if (!selectedSlot) return; setSubmitting(true); setNotice(""); try { await api("/api/appointments/request", { method: "POST", body: JSON.stringify({ reason, requestedDate: selectedSlot.date, requestedStartTime: selectedSlot.startTime, requestedEndTime: selectedSlot.endTime, meetingMethod: selectedSlot.meetingMethod, location: selectedSlot.location ?? undefined, availabilityEntryId: selectedSlot.id }) }); setSelectedSlot(null); setNotice("Your request was submitted for review."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to submit the request."); } finally { setSubmitting(false); } }
  return <section className="appointments page"><h1>Request an appointment</h1><p className="muted">Choose a reason and an available time with your spiritual father.</p><div className="reasons">{reasons.map((item) => <button className={reason === item.value ? "selected" : ""} key={item.value} onClick={() => setReason(item.value)} type="button">{item.label}</button>)}</div>{loading ? <p>Loading available times…</p> : <div className="slots">{slots.length ? slots.map((slot) => <button className={selectedSlot?.id === slot.id ? "slot selected" : "slot"} key={slot.id} onClick={() => setSelectedSlot(slot)} type="button"><strong>{new Date(`${slot.date}T12:00:00`).toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric" })}</strong><span>{slot.startTime.slice(0, 5)} – {slot.endTime.slice(0, 5)}</span><small>{slot.meetingMethod}{slot.location ? ` · ${slot.location}` : ""}</small></button>) : <p className="empty-inline">No available slots yet.</p>}</div>}<button className="primary book" disabled={!selectedSlot || submitting} onClick={() => void submitRequest()} type="button">{submitting ? "Sending request…" : selectedSlot ? `Confirm ${selectedSlot.startTime.slice(0, 5)}` : "Select a time"}</button>{notice ? <p className={notice.startsWith("Your") ? "success" : "error"}>{notice}</p> : null}<h2>My requests</h2><div className="request-list">{requests.length ? requests.map((request) => <AppointmentCard appointment={request} key={request.id} />) : <p className="empty-inline">No appointment requests yet.</p>}</div></section>;
}
