import { CalendarCheck, CalendarClock, ChevronLeft, ChevronRight, Plus } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { AppointmentCard, type ChildAppointment } from "../components/appointments/AppointmentCard";
import { api } from "../services";
import "./appointmentsPage.css";
import "./appointmentsRequestExact.css";
import "./appointmentReasonSimple.css";
import "./appointmentReasonAutoSize.css";
import "./appointmentCalendarCompact.css";
import "./appointmentSlotAction.css";
import "./appointmentRequestsExact.css";

type AppointmentReason = "confession" | "spiritual-guidance" | "counseling" | "repentance" | "family-issue" | "other";
type Slot = { id: string; date: string; startTime: string; endTime: string; meetingMethod: string; location?: string | null; notes?: string | null };
type Step = "reasons" | "date" | "time" | "confirmed";
type ReasonInfo = { value: AppointmentReason; label: string; description: string };
const reasons: ReasonInfo[] = [{ value: "confession", label: "Confession", description: "Sacrament of Reconciliation" }, { value: "spiritual-guidance", label: "Spiritual Guidance", description: "Spiritual advice and teaching" }, { value: "counseling", label: "Counseling", description: "Personal or emotional support" }, { value: "repentance", label: "Repentance", description: "Seeking spiritual renewal" }, { value: "family-issue", label: "Family Issue", description: "Family problems and relationships" }, { value: "other", label: "Other", description: "Other reason not listed above" }];
const weekdays = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];

const keyOf = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const longDate = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" });
const timeLabel = (time: string) => new Date(`2000-01-01T${time}`).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" });
const labelReason = (value: AppointmentReason | null) => reasons.find((reason) => reason.value === value)?.label ?? "Appointment";
function duration(start: string, end: string) { const [sh, sm] = start.split(":").map(Number); const [eh, em] = end.split(":").map(Number); return (eh * 60 + em) - (sh * 60 + sm); }

export function AppointmentsPage() {
  const [tab, setTab] = useState<"request" | "requests">("request"); const [step, setStep] = useState<Step>("reasons"); const [reason, setReason] = useState<AppointmentReason | null>(null); const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [slots, setSlots] = useState<Slot[]>([]); const [requests, setRequests] = useState<ChildAppointment[]>([]); const [selectedDate, setSelectedDate] = useState<string | null>(null); const [selectedSlot, setSelectedSlot] = useState<Slot | null>(null); const [loading, setLoading] = useState(false); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState("");
  const monthRange = useMemo(() => ({ startDate: keyOf(new Date(month.getFullYear(), month.getMonth(), 1)), endDate: keyOf(new Date(month.getFullYear(), month.getMonth() + 1, 0)) }), [month]);
  const datesWithSlots = useMemo(() => new Set(slots.map((slot) => slot.date)), [slots]);
  const daySlots = useMemo(() => slots.filter((slot) => slot.date === selectedDate), [slots, selectedDate]);
  const availableDates = useMemo(() => [...datesWithSlots].sort(), [datesWithSlots]);
  const calendar = useMemo(() => { const blank = new Date(month.getFullYear(), month.getMonth(), 1).getDay(); const total = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return [...Array(blank).fill(null), ...Array.from({ length: total }, (_, index) => new Date(month.getFullYear(), month.getMonth(), index + 1))]; }, [month]);

  async function loadSlots() { setLoading(true); setMessage(""); try { const data = await api<{ slots?: Slot[] }>(`/api/appointments/slots?startDate=${monthRange.startDate}&endDate=${monthRange.endDate}`); setSlots(data.slots ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load available times."); } finally { setLoading(false); } }
  async function loadRequests() { setLoading(true); setMessage(""); try { const data = await api<{ requests?: ChildAppointment[] }>("/api/appointments/request?type=requests"); setRequests(data.requests ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load requests."); } finally { setLoading(false); } }
  useEffect(() => { if (step === "date" || step === "time") void loadSlots(); }, [monthRange.startDate, monthRange.endDate, step]);
  useEffect(() => { if (tab === "requests") void loadRequests(); }, [tab]);
  function chooseReason(value: AppointmentReason) { setReason(value); setSelectedDate(null); setSelectedSlot(null); }
  async function submit() { if (!reason || !selectedSlot) return; setSubmitting(true); setMessage(""); try { await api("/api/appointments/request", { method: "POST", body: JSON.stringify({ reason, requestedDate: selectedSlot.date, requestedStartTime: selectedSlot.startTime, requestedEndTime: selectedSlot.endTime, meetingMethod: selectedSlot.meetingMethod, location: selectedSlot.location ?? undefined, availabilityEntryId: selectedSlot.id }) }); setStep("confirmed"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to send your request."); } finally { setSubmitting(false); } }
  async function deleteRequest(request: ChildAppointment, edit = false) { try { await api(`/api/appointments/request/${request.id}`, { method: "DELETE" }); setRequests((current) => current.filter((item) => item.id !== request.id)); if (edit) { setReason(request.reason as AppointmentReason); setSelectedDate(request.requestedDate); setTab("request"); setStep("date"); } } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update this request."); } }
  function reset() { setStep("reasons"); setReason(null); setSelectedDate(null); setSelectedSlot(null); setMessage(""); }
  const changeMonth = (value: number) => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + value, 1));

  if (step === "confirmed" && selectedSlot) return <section className="appointment-page"><section className="appointment-confirmed"><CalendarCheck /><h1>Request Submitted!</h1><p>Your <b>{labelReason(reason)}</b> request for <b>{longDate(selectedSlot.date)} at {timeLabel(selectedSlot.startTime)}</b> has been sent to your Spiritual Father.</p><button className="appointment-primary" onClick={reset} type="button">Back to Appointments</button><button className="appointment-link" onClick={() => { reset(); setTab("requests"); }} type="button">View My Requests →</button></section></section>;

  if (step === "date") return <section className="appointment-page"><AppointmentSelection reason={labelReason(reason)} onChange={reset} /><section className="appointment-calendar"><div className="calendar-title"><button aria-label="Previous month" onClick={() => changeMonth(-1)} type="button"><ChevronLeft /></button><h1>{month.toLocaleDateString(undefined, { month: "long", year: "numeric" })}</h1><button aria-label="Next month" onClick={() => changeMonth(1)} type="button"><ChevronRight /></button></div><div className="calendar-weekdays">{weekdays.map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{calendar.map((day, index) => { if (!day) return <span key={`blank-${index}`} />; const date = keyOf(day); const available = datesWithSlots.has(date); const selected = selectedDate === date; return <button className={`${available ? "available" : ""} ${selected ? "selected" : ""}`} disabled={!available} key={date} onClick={() => setSelectedDate(date)} type="button">{day.getDate()}</button>; })}</div><div className="calendar-legend"><span><i className="today" /> Available</span><span><i /> Unavailable</span></div></section>{message ? <p className="appointment-error">{message}</p> : null}<button className="appointment-primary" disabled={!selectedDate} onClick={() => selectedDate && setStep("time")} type="button"><CalendarCheck /> Select a Date</button></section>;

  if (step === "time") return <section className="appointment-page"><AppointmentSelection date={selectedDate ? longDate(selectedDate) : undefined} reason={labelReason(reason)} onChange={() => setStep("date")} /><div className="appointment-date-tabs">{availableDates.map((date) => <button className={date === selectedDate ? "active" : ""} key={date} onClick={() => { setSelectedDate(date); setSelectedSlot(null); }} type="button"><b>{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: "short" })}</b><strong>{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</strong><small>{slots.filter((slot) => slot.date === date).length} slots</small></button>)}</div><div className="slots-heading"><b>{daySlots.length} slots available</b><span>Your Spiritual Father</span></div>{loading ? <p className="appointment-empty">Loading available times…</p> : daySlots.length ? <div className="appointment-slots">{daySlots.map((slot) => <button className={selectedSlot?.id === slot.id ? "selected" : ""} key={slot.id} onClick={() => setSelectedSlot(slot)} type="button"><div><b>{timeLabel(slot.startTime)}</b><i>+</i><b>{timeLabel(slot.endTime)}</b></div><p>{Number(slot.startTime.slice(0, 2)) < 12 ? "Morning" : "Afternoon"} session · {slot.meetingMethod.replace("-", " ")} <strong>{duration(slot.startTime, slot.endTime)} min</strong></p><small><em>{selectedSlot?.id === slot.id ? "Selected" : "Select →"}</em></small></button>)}</div> : <p className="appointment-empty">No available slots for this date.</p>}{message ? <p className="appointment-error">{message}</p> : null}<button className="appointment-primary" disabled={!selectedSlot || submitting} onClick={() => void submit()} type="button">{submitting ? "Sending request…" : selectedSlot ? `Confirm — ${timeLabel(selectedSlot.startTime)}` : "Select a Time Slot"}</button></section>;

  return <section className="appointment-page appointment-list"><div className="appointment-tabs"><button className={tab === "request" ? "active" : ""} onClick={() => setTab("request")} type="button">Request</button><button className={tab === "requests" ? "active" : ""} onClick={() => setTab("requests")} type="button">My Requests</button></div>{tab === "request" ? <><section className="appointment-reasons"><h1>What would you like to discuss?</h1><p>Select one reason and we’ll show the available times with your spiritual father.</p><div>{reasons.map((item) => <button className={reason === item.value ? "selected" : ""} key={item.value} onClick={() => chooseReason(item.value)} type="button"><i><b>{item.label}</b></i><ChevronRight /></button>)}</div></section>{reason ? <div className="appointment-selected"><i /> <span>Selected:</span> <b>{labelReason(reason)}</b></div> : null}<button className="appointment-primary appointment-choose" disabled={!reason} onClick={() => reason && setStep("date")} type="button"><CalendarCheck /> Choose Date & Time</button></> : <section className="appointment-requests">{loading ? <p className="appointment-empty">Loading requests…</p> : message ? <p className="appointment-error">{message}</p> : requests.length ? requests.map((request) => <AppointmentCard appointment={request} key={request.id} onDelete={() => void deleteRequest(request)} onEdit={() => void deleteRequest(request, true)} />) : <p className="appointment-empty"><CalendarClock /> No appointment requests yet.</p>}</section>}</section>;
}

function AppointmentSelection({ reason, date, onChange }: { reason: string; date?: string; onChange: () => void }) { return <section className="appointment-selection"><span><Plus /></span><div><b>{reason}</b>{date ? <small>{date}</small> : null}</div><button onClick={onChange} type="button">{date ? "Change date" : "Change"}</button></section>; }
