import { CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, UserRound } from "lucide-react";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { useNavigate } from "react-router-dom";

import "./registerPage.css";

type ApiResponse = { challengeId?: string; registrationToken?: string; resendAfterSeconds?: number; message?: string };

async function postRegistration(path: string, body: unknown) {
  const baseUrl = import.meta.env.VITE_API_BASE_URL?.replace(/\/$/, "");
  if (!baseUrl) throw new Error("This app has not been configured with its Vercel API URL.");
  const response = await fetch(`${baseUrl}${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const data = await response.json().catch(() => ({})) as ApiResponse;
  if (!response.ok) throw new Error(data.message || "Something went wrong. Please try again.");
  return data;
}

export function RegisterPage() {
  const navigate = useNavigate();
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [challengeId, setChallengeId] = useState(""); const [code, setCode] = useState(""); const [token, setToken] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [showConfirm, setShowConfirm] = useState(false); const [busy, setBusy] = useState<"send" | "verify" | "create" | "">(""); const [cooldown, setCooldown] = useState(0); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [created, setCreated] = useState(false);
  const codeSent = Boolean(challengeId); const verified = Boolean(token);
  useEffect(() => { if (!cooldown) return; const timer = window.setInterval(() => setCooldown((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [cooldown]);
  useEffect(() => { if (!created) return; const timer = window.setTimeout(() => navigate("/", { replace: true }), 2200); return () => window.clearTimeout(timer); }, [created, navigate]);
  function clearFeedback() { setError(""); setMessage(""); }
  async function sendCode() { clearFeedback(); if (name.trim().length < 2) return setError("Enter your baptismal name."); if (!email.trim()) return setError("Enter your email address."); setBusy("send"); try { const result = await postRegistration("/api/registration/send-code", { email }); if (!result.challengeId) throw new Error("Something went wrong. Please try again."); setChallengeId(result.challengeId); setCode(""); setToken(""); setCooldown(result.resendAfterSeconds ?? 60); setMessage(`A six-digit code was sent to ${email.trim().toLowerCase()}.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Something went wrong. Please try again."); } finally { setBusy(""); } }
  async function verifyCode() { clearFeedback(); if (!/^\d{6}$/.test(code)) return setError("Enter the six-digit verification code."); setBusy("verify"); try { const result = await postRegistration("/api/registration/verify-code", { challengeId, email, code }); if (!result.registrationToken) throw new Error("Something went wrong. Please try again."); setToken(result.registrationToken); setMessage("Email verified. Create your password to continue."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Something went wrong. Please try again."); } finally { setBusy(""); } }
  async function createAccount(event: FormEvent) { event.preventDefault(); clearFeedback(); if (!verified) return setError("Verify your email before creating an account."); if (password.length < 10) return setError("The password must contain at least 10 characters."); if (password !== confirmPassword) return setError("The passwords do not match."); setBusy("create"); try { await postRegistration("/api/registration/create-account", { challengeId, registrationToken: token, baptismalName: name, email, password, confirmPassword }); setCreated(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Something went wrong. Please try again."); } finally { setBusy(""); } }
  if (created) return <main className="register-page"><section className="register-success"><CheckCircle2 /><h1>Account Created Successfully</h1><p>Your Spiritual Child account is ready. You can now sign in using your email and password.</p><small>Returning to sign in…</small></section></main>;
  return <main className="register-page"><section className="register-card"><button className="register-back" onClick={() => navigate(-1)} type="button">‹</button><img alt="Abune" className="register-logo" src="/images/logo.png" /><h1>Create Your Account</h1><p>Register to connect with your spiritual father and begin your spiritual journey.</p><form onSubmit={createAccount}><Field icon={<UserRound />} label="Baptismal Name" onChange={setName} placeholder="Baptismal Name" value={name} disabled={codeSent} /><div className="register-email"><Field icon={<Mail />} label="Email" onChange={setEmail} placeholder="Email" type="email" value={email} disabled={codeSent} /><button disabled={Boolean(busy) || (codeSent && cooldown > 0) || verified} onClick={() => void sendCode()} type="button">{busy === "send" ? "Sending…" : codeSent ? cooldown ? `Resend ${cooldown}s` : "Resend" : "Send Code"}</button></div>{codeSent && !verified ? <><Field icon={<ShieldCheck />} label="Verification Code" maxLength={6} onChange={(value) => setCode(value.replace(/\D/g, "").slice(0, 6))} placeholder="Verification Code" value={code} /><div className="register-verify"><button disabled={Boolean(busy)} onClick={() => void verifyCode()} type="button">{busy === "verify" ? "Verifying…" : "Verify Code"}</button></div></> : null}{verified ? <><PasswordField label="Password" onChange={setPassword} show={showPassword} toggle={() => setShowPassword((value) => !value)} value={password} /><PasswordField label="Confirm Password" onChange={setConfirmPassword} show={showConfirm} toggle={() => setShowConfirm((value) => !value)} value={confirmPassword} /><small className="register-hint">Use at least 10 characters.</small></> : null}{error ? <p className="register-error">{error}</p> : null}{message ? <p className="register-message">{message}</p> : null}{verified ? <button className="register-submit" disabled={Boolean(busy)} type="submit">{busy === "create" ? "Creating Account…" : "Create Account"}</button> : null}</form><p className="register-login">Already have an account? <button onClick={() => navigate("/")} type="button">Sign In</button></p></section></main>;
}
function Field({ icon, label, onChange, value, placeholder, type = "text", disabled, maxLength }: { icon: ReactNode; label: string; onChange: (value: string) => void; value: string; placeholder: string; type?: string; disabled?: boolean; maxLength?: number }) { return <label className="register-field" data-label={label}>{icon}<input disabled={disabled} maxLength={maxLength} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} type={type} value={value} /></label>; }
function PasswordField({ label, onChange, show, toggle, value }: { label: string; onChange: (value: string) => void; show: boolean; toggle: () => void; value: string }) { return <label className="register-field" data-label={label}><LockKeyhole /><input minLength={10} onChange={(event) => onChange(event.target.value)} placeholder={label} type={show ? "text" : "password"} value={value} /><button aria-label={show ? "Hide password" : "Show password"} onClick={toggle} type="button">{show ? <Eye /> : <EyeOff />}</button></label>; }
